version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - biomejs
  - crxjs
  - defg
  - dotenvx
  - nolookalikes
  - piku
  - pkgroll
  - qrcode
  - supabase
  - syncpack
  - vite
  - youtu.be
import: []
